# Generated by Django 4.1.1 on 2022-09-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='адрес фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_modified', models.DateTimeField(auto_now=True, verbose_name='вермя изменения')),
                ('is_onsite', models.BooleanField(default=True, verbose_name='публикация')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balloon.group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Шар',
                'verbose_name_plural': 'Шары',
                'ordering': ['time_modified'],
            },
        ),
    ]
