# Generated by Django 4.1.1 on 2022-09-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0002_group_balloon_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balloon',
            options={'ordering': ['time_modified'], 'verbose_name': 'Шар', 'verbose_name_plural': 'Шары'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='balloon',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='balloon.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='is_onsite',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='адрес фото'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='вермя изменения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название'),
        ),
    ]
