# Generated by Django 4.1.2 on 2022-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0003_alter_review_options_alter_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/reviews_photo', verbose_name='адрес фото'),
        ),
    ]
