# Generated by Django 4.1.2 on 2022-10-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0004_alter_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/reviews_photo', verbose_name='адрес фото'),
        ),
    ]
